# Generated by Django 5.1.7 on 2025-04-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_friendship_is_accepted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="OTPVerification",
        ),
    ]
