# Generated by Django 5.2 on 2025-04-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_verificationcode_remove_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketplace",
            name="upi_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="marketplace",
            name="price",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
