# Generated by Django 5.1.7 on 2025-04-07 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_group_id_alter_group_members_chat_message_chat_and_more"),
        ("api", "0008_remove_customuser_phone_number_and_more"),
    ]

    operations = []
