# Generated by Django 5.2 on 2025-04-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_customuser_address_alter_customuser_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marketplace",
            name="image",
            field=models.TextField(blank=True, null=True),
        ),
    ]
