# Generated by Django 5.2 on 2025-04-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_marketplace_image"),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE api_marketplace MODIFY COLUMN image MEDIUMTEXT NULL;",
            reverse_sql="ALTER TABLE api_marketplace MODIFY COLUMN image TEXT NULL;",
        )
    ]
